version: '2.1'
services:
  app:
    build: .
    dns:
     - 8.8.8.8
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
      ENTRYPOINT: app
    ports:
      - 3002:3000
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
